<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Extensions\Extensions.csproj" />
    <ProjectReference Include="..\GrainInterfaces\GrainInterfaces.csproj" />
    <ProjectReference Include="..\Grains\Grains.csproj" />
    <ProjectReference Include="..\Silo\Silo.csproj" />
    <ProjectReference Include="..\Translators\Translators.csproj" />
    <ProjectReference Include="..\Client\Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute" />
  </ItemGroup>

</Project>
